spring:
  application:
    name: "gatewayserver"
  config:
    import: "optional:configserver:http://localhost:8071"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lowerCaseServiceId: true

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true

info:
  app:
    name: "gatewayserver"
    description: "Eazy gatewayserver Application"
    version: "1.0.0"

logging:
  level:
    com:
      eazy:
        gatewayserver: DEBUG